import os
import random
import logging
from dotenv import load_dotenv
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes

# Carga variables de entorno
load_dotenv()
TOKEN = os.getenv("BOT_TOKEN")

# Configura logging (opcional pero recomendado)
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

ESTILOS = {
    "motivacion": [
        "A veces no estás cansado, estás saturado. Respira.",
        "No todo tiene que doler para valer la pena.",
        "Vas mejor de lo que crees.",
        "Cada paso cuenta, aunque no lo notes hoy.",
        "Lo importante no es la velocidad, sino seguir adelante.",
        "Si caes siete veces, levántate ocho.",
        "El éxito es la suma de pequeños esfuerzos diarios.",
        "La disciplina vence a la motivación cuando esta falla.",
        "Tu esfuerzo de hoy es la victoria de mañana.",
        "No te rindas, los grandes logros toman tiempo.",
        "Eres más fuerte de lo que imaginas.",
        "Las excusas no construyen tu futuro.",
        "Hazlo por ti, no por demostrar a nadie.",
        "Cuando quieras abandonar, piensa en por qué empezaste.",
        "Un día a la vez, paso a paso.",
        "Los límites solo existen en tu mente.",
        "Construye hábitos, no esperes inspiración.",
        "Tu mejor inversión es en ti mismo.",
        "Cambia tus hábitos, cambia tu vida.",
        "La constancia es la llave del éxito.",
        "Nunca es tarde para volver a empezar.",
        "Aprende de los errores, no te detengas en ellos.",
        "Los sueños sin acción son solo ilusiones.",
        "Pequeñas victorias crean grandes cambios.",
        "Tu esfuerzo es el lenguaje de tu futuro yo.",
        "No busques la perfección, busca el progreso.",
        "Haz que cada día cuente.",
        "El cambio comienza con una decisión.",
        "Cree en ti, aunque otros duden.",
        "La paciencia es poder.",
        "El sacrificio de hoy será tu orgullo mañana.",
        "La motivación se crea, no se espera.",
        "Solo tú puedes cambiar tu historia.",
        "Construye una rutina que te empodere.",
        "No es sobre ser el mejor, es sobre ser mejor que ayer.",
        "La fuerza está en seguir, no en empezar.",
        "Tu mente es tu mejor herramienta, úsala bien.",
        "Los hábitos moldean tu destino.",
        "Lo imposible es solo una opinión.",
        "Cada amanecer es una nueva oportunidad.",
        "El camino al éxito está siempre en construcción.",
        "No dejes para mañana lo que puedes empezar hoy.",
        "Tu potencial es ilimitado.",
        "Conviértete en la persona que admiras.",
        "La persistencia es la clave del triunfo.",
        "No cuentes los días, haz que los días cuenten.",
        "El fracaso es una lección, no una derrota.",
        "Visualiza tus metas y trabaja por ellas.",
        "La grandeza está en los pequeños detalles.",
        "Supera tus miedos y alcanzarás tus sueños.",
        "Sé la energía que quieres atraer.",
        "Tu actitud determina tu dirección.",
        "No hay atajos para los lugares que valen la pena.",
        "El único límite eres tú mismo.",
        "Crea tu propia suerte con trabajo duro.",
        "La vida te pone a prueba para hacerte más fuerte.",
        "Transforma tus heridas en sabiduría.",
        "El éxito no es final, el fracaso no es fatal: es el coraje de continuar lo que cuenta.",
        "Tu historia apenas comienza.",
        "Sé valiente para empezar, sé fuerte para continuar.",
        "No esperes el momento perfecto, toma el momento y hazlo perfecto.",
        "Cada obstáculo es una oportunidad de crecimiento.",
        "La confianza en ti mismo es tu mejor arma.",
        "El esfuerzo de hoy es el descanso de mañana.",
        "No te compares con los demás, compárate contigo mismo de ayer.",
        "La vida es un eco, lo que envías, regresa.",
        "El primer paso es el más difícil, pero el más importante.",
        "Tu futuro se crea con lo que haces hoy, no mañana."
    ],
    "reflexion": [
        "Hay silencios que dicen más que mil palabras.",
        "A veces, estar solo no es estar vacío.",
        "Escucha tu voz interna antes que la externa.",
        "No temas al cambio, teme a quedarte igual.",
        "Las heridas más profundas no se ven.",
        "El tiempo cura lo que la razón no puede.",
        "No busques fuera lo que tienes dentro.",
        "Aprender a soltar es crecer.",
        "El verdadero valor está en la vulnerabilidad.",
        "Cada final es un nuevo comienzo disfrazado.",
        "La paciencia es el arte de esperar sin perder la calma.",
        "Saber quién eres es el mayor desafío.",
        "La tristeza también enseña lecciones.",
        "No todo está en tus manos, aprende a fluir.",
        "Las preguntas correctas son más valiosas que las respuestas fáciles.",
        "El ego es la sombra de la inseguridad.",
        "El silencio a veces es el mejor refugio.",
        "Aprende a escucharte sin juzgarte.",
        "La luz más fuerte surge de la oscuridad más profunda.",
        "No hay sombra sin luz.",
        "Tu historia no define tu destino.",
        "Lo que duele también transforma.",
        "Cada cicatriz es una historia de supervivencia.",
        "El amor propio es un acto revolucionario.",
        "Deja que las lágrimas limpien tu alma.",
        "La vida es un equilibrio entre perder y ganar.",
        "No confundas soledad con aislamiento.",
        "El miedo es un maestro, no un enemigo.",
        "A veces hay que perder para encontrar.",
        "La verdad a veces duele, pero libera.",
        "No te aferres a lo que te lastima.",
        "El crecimiento viene del desconcierto.",
        "Las palabras tienen poder, elige las tuyas.",
        "La compasión comienza contigo mismo.",
        "Cada día es una página en blanco.",
        "No busques la felicidad, crea sentido.",
        "El cambio duele, pero la resistencia duele más.",
        "El pasado es un lugar de referencia, no de residencia.",
        "Ser honesto contigo es el primer paso.",
        "La verdadera sabiduría está en reconocer la propia ignorancia.",
        "La vida no se mide por las veces que respiras, sino por los momentos que te dejan sin aliento.",
        "El mayor viaje es el interior.",
        "A veces, la respuesta está en dejar de buscar.",
        "La autenticidad es tu mayor fortaleza.",
        "No puedes controlar todo, pero sí tu reacción.",
        "La felicidad no es un destino, es una forma de viajar.",
        "El perdón libera al que perdona.",
        "Observa sin juzgar, escucha sin interrumpir.",
        "La belleza está en la imperfección.",
        "Cada experiencia te moldea, buena o mala.",
        "La verdadera riqueza es la paz mental.",
        "Las decisiones pequeñas construyen grandes destinos.",
        "El arte de vivir es saber cuándo soltar y cuándo aferrarse.",
        "La gratitud transforma lo que tienes en suficiente.",
        "No te definas por tus errores, sino por lo que aprendes de ellos.",
        "El presente es el único momento que existe.",
        "La empatía es ver con los ojos del otro.",
        "La libertad es ser quien eres sin pedir permiso.",
        "La calma no es la ausencia de tormenta, sino la paz en medio de ella.",
        "La vida es un eco, lo que envías, regresa.",
        "A veces, el silencio es la mejor respuesta.",
        "El cambio es la única constante.",
        "La verdadera fuerza reside en la resiliencia.",
        "No todo lo que se enfrenta se puede cambiar, pero nada se cambia si no se enfrenta.",
        "El autoconocimiento es el inicio de toda sabiduría.",
        "La vida es un regalo, desempaquétala con curiosidad.",
        "No te arrepientas de lo que hiciste, sino de lo que no intentaste.",
        "La simplicidad es la máxima sofisticación."
    ],
    "carino": [
        "No pasa nada si hoy no puedes con todo.",
        "Estás haciendo lo mejor que puedes.",
        "Te mereces calma, aunque nadie te la dé.",
        "Eres importante, incluso cuando no lo sientes.",
        "Date permiso para descansar sin culpa.",
        "Tus emociones son válidas, déjalas salir.",
        "Abrazarte a ti mismo es un acto de amor.",
        "Nadie es perfecto, y está bien así.",
        "El cariño propio es un refugio seguro.",
        "No estás solo, aunque a veces lo parezca.",
        "Vales más de lo que crees.",
        "Cuida de ti como cuidarías a un amigo.",
        "Está bien pedir ayuda cuando la necesitas.",
        "Eres digno de amor y respeto.",
        "Permítete sentir sin juzgarte.",
        "Celebra cada pequeño logro personal.",
        "La paciencia contigo es fundamental.",
        "Los días difíciles no definen quién eres.",
        "Tu bienestar es una prioridad.",
        "A veces solo necesitas un respiro.",
        "No tienes que ser fuerte siempre.",
        "Tu historia merece ser escuchada.",
        "No te compares, tu camino es único.",
        "Reconoce tu valor aunque nadie más lo haga.",
        "Eres suficiente tal como eres.",
        "Date tiempo para sanar y crecer.",
        "Los errores no disminuyen tu valor.",
        "Eres un ser en constante evolución.",
        "Cuídate con la misma ternura que cuidas a otros.",
        "El amor comienza desde dentro.",
        "Eres luz, incluso en días grises.",
        "No te olvides de ser amable contigo mismo.",
        "Cada día es una nueva oportunidad para quererte.",
        "Abraza tus imperfecciones con cariño.",
        "Tu corazón merece cuidado y respeto.",
        "Sé tu mejor compañía.",
        "A veces la mejor ayuda es escucharte.",
        "Tu bienestar emocional importa.",
        "Tómate un momento para ti.",
        "Permítete ser vulnerable, es una fortaleza.",
        "Tu paz interior es invaluable.",
        "No te exijas más de lo que puedes dar.",
        "Eres un universo de posibilidades.",
        "Confía en tu proceso, todo llega a su tiempo.",
        "Tu voz importa, hazla escuchar.",
        "Los pequeños gestos de amor propio son los más grandes.",
        "Elige la calma sobre el caos.",
        "Eres capaz de mucho más de lo que imaginas.",
        "Date permiso para sentir, para vivir, para ser.",
        "La compasión por ti mismo es el primer paso.",
        "Tu salud mental es tan importante como la física.",
        "No te abandones a ti mismo.",
        "Eres resiliente, lo has demostrado antes.",
        "Rodéate de lo que te hace bien.",
        "Tu felicidad es tu responsabilidad.",
        "Acepta tus sombras, son parte de ti.",
        "No te castigues por lo que no puedes controlar.",
        "Eres un milagro, recuérdalo.",
        "El amor propio es el inicio de una aventura que dura toda la vida.",
        "Honra tus límites y tus deseos.",
        "Tu energía es valiosa, protégela.",
        "Sé tu propio refugio en la tormenta.",
        "La vida es un viaje, sé amable contigo en el camino.",
        "Cada día es una oportunidad para empezar de nuevo contigo.",
        "No necesitas la aprobación de nadie para ser feliz.",
        "Tu valor no depende de lo que haces, sino de lo que eres.",
        "Escucha a tu cuerpo, te habla.",
        "Eres suficiente, siempre lo has sido.",
        "Permítete florecer a tu propio ritmo."
    ],
    "toques": [
        "Levántate. Nadie lo hará por ti.",
        "¿Hasta cuándo vas a esperar para cuidarte?",
        "No le debes explicación a nadie, pero sí a ti.",
        "El cambio no espera a nadie.",
        "Deja de buscar excusas y actúa.",
        "Tu zona de confort es tu mayor enemigo.",
        "Hazlo ahora, el momento perfecto no existe.",
        "Sin esfuerzo no hay recompensa.",
        "Si no luchas por tus sueños, alguien más te contratará para luchar por los suyos.",
        "El dolor es temporal, el orgullo es para siempre.",
        "No esperes a sentir ganas para empezar.",
        "El fracaso es parte del camino, no el final.",
        "Los límites solo existen si tú los aceptas.",
        "Ponte metas altas o quédate donde estás.",
        "El tiempo perdido no vuelve.",
        "No eres víctima, eres responsable.",
        "La disciplina es el puente entre metas y logros.",
        "Deja de quejarte y haz algo.",
        "Solo tú puedes cambiar tu historia.",
        "Sin acción no hay resultados.",
        "La comodidad es la cárcel invisible.",
        "Si quieres resultados, trabaja por ellos.",
        "No esperes motivación, crea disciplina.",
        "El éxito se construye a diario.",
        "Si no arriesgas, no ganas.",
        "No culpes a nadie por tu falta de progreso.",
        "Haz que tu esfuerzo hable por ti.",
        "Nada cambia si tú no cambias.",
        "Levántate temprano, la vida no espera.",
        "El momento es ahora, no mañana.",
        "No pongas límites a tu potencial.",
        "No permitas que el miedo te detenga.",
        "Toma control de tu vida.",
        "El que quiere puede, el que no, busca excusas.",
        "Deja de soñar y empieza a hacer.",
        "El éxito requiere sacrificio.",
        "El único fracaso es no intentarlo.",
        "Haz lo que otros no quieren para lograr lo que otros no tienen.",
        "Deja de posponer. La vida pasa.",
        "Tu futuro se construye hoy, no con intenciones.",
        "Si no te gusta, cámbialo. Si no puedes cambiarlo, cambia tu actitud.",
        "Menos palabras, más acción.",
        "La autocompasión no construye imperios.",
        "Sal de tu cabeza y entra en tu vida.",
        "El mundo no te debe nada, sal y gánatelo.",
        "Deja de esperar a que las cosas pasen, haz que pasen.",
        "Si no te esfuerzas, no hay crecimiento.",
        "La inacción es el peor de los fracasos.",
        "¿Qué estás esperando para empezar?",
        "Tu potencial no tiene fecha de caducidad.",
        "No te compares con nadie, supera tu versión anterior.",
        "El miedo es una elección, no un destino.",
        "La vida es corta para no arriesgarse.",
        "No hay progreso sin incomodidad.",
        "Haz que tu trabajo sea tu mejor carta de presentación.",
        "Las oportunidades no llaman a la puerta de los que esperan.",
        "Deja de quejarte, empieza a crear.",
        "El único camino es hacia adelante.",
        "No hay tiempo para la mediocridad.",
        "Si no te desafías, no creces.",
        "El éxito no es suerte, es trabajo.",
        "No te conformes con menos de lo que mereces.",
        "La mediocridad es una elección.",
        "Tu vida es tu responsabilidad, tómala.",
        "Deja de ser tu propio obstáculo.",
        "El dolor de la disciplina es menor que el dolor del arrepentimiento.",
        "No hay excusas, solo resultados.",
        "Sé el arquitecto de tu propio destino."
    ],
    "minimalismo": [
        "Respira.",
        "Sigue.",
        "Confía.",
        "Paz.",
        "Calma.",
        "Ahora.",
        "Ser.",
        "Fluye.",
        "Sencillo.",
        "Libre.",
        "Pausa.",
        "Luz.",
        "Aquí.",
        "Fácil.",
        "Claro.",
        "Quietud.",
        "Momento.",
        "Gratitud.",
        "Espera.",
        "Sólido.",
        "Amor.",
        "Silencio.",
        "Conecta.",
        "Tiempo.",
        "Abraza.",
        "Sincero.",
        "Libre.",
        "Sueña.",
        "Equilibrio.",
        "Simple.",
        "Tranquilo.",
        "Ligero.",
        "Firme.",
        "Natural.",
        "Suave.",
        "Luminoso.",
        "Valiente.",
        "Armonía.",
        "Sereno.",
        "Menos.",
        "Esencia.",
        "Vive.",
        "Suelta.",
        "Presente.",
        "Acepta.",
        "Foco.",
        "Crea.",
        "Disfruta.",
        "Desconecta.",
        "Suficiente.",
        "Verdad.",
        "Espacio.",
        "Pura.",
        "Siente.",
        "Escucha.",
        "Calma.",
        "Real.",
        "Fuerza.",
        "Alma.",
        "Fluye.",
        "Consciente.",
        "Despeja.",
        "Aprecia.",
        "Esencial.",
        "Puro.",
        "Auténtico.",
        "Serenidad.",
        "Paz.",
        "Aquí.",
        "Ahora.",
        "Libera.",
        "Agradece.",
        "Menos es más.",
        "Vive simple.",
        "Enfócate.",
        "Sé tú.",
        "Silencia.",
        "Expande.",
        "Conecta.",
        "Despierta."
    ],
}

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "👋 ¡Hola! Soy TuEcoBot.\n"
        "Te enviaré mensajes emocionales cada día.\n"
        "Usa /mensaje para recibir uno ahora."
    )

async def mensaje(update: Update, context: ContextTypes.DEFAULT_TYPE):
    estilo = random.choice(list(ESTILOS.values()))
    frase = random.choice(estilo)
    await update.message.reply_text(f"💬 {frase}")

def main():
    app = ApplicationBuilder().token(TOKEN).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("mensaje", mensaje))

    print("Bot encendido...")
    app.run_polling()

if __name__ == "__main__":
    main()

